using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using DocGenerator.Model;

namespace DocGenerator.Markdown;

/// <summary>
/// The single Markdown generator shared by every language. It takes a fully-resolved
/// <see cref="ApiModel"/> and writes a consistent reference tree:
///
/// <code>
/// docs/reference/&lt;lang&gt;/
///   index.md                 # language overview (sidebar_position 0)
///   &lt;Namespace&gt;/
///     index.md               # namespace page (tables of its types)
///     _category_.yml         # label + unique i18n key
///     &lt;TypeName&gt;.md          # ONE page per type, members grouped inline + anchors
/// </code>
///
/// For "flat" languages (a single namespace whose <see cref="ApiNamespace.Name"/> is
/// <c>""</c> — JS / C / Python) the namespace folder is skipped and type pages live
/// directly under the language directory.
///
/// <para><b>Link contract.</b> Adapters set <see cref="ApiTypeRef.Href"/> to a path
/// <i>relative to the language root</i> (use <see cref="PageHref"/> / <see cref="MemberHref"/>
/// to build it). The writer rebases each href to be relative to the page currently being
/// rendered, so links always resolve to <c>./Type.md#anchor</c> or <c>../Ns/Type.md</c>.</para>
/// </summary>
internal static class MarkdownWriter
{
    private const string AutoGenComment = "<!-- auto-generated by generator/ — do not edit -->";

    // Language id for member code fences, set once at the start of Write().
    [ThreadStatic] private static string? _lang;

    public static void Write(ApiModel model, string outputDir)
    {
        Directory.CreateDirectory(outputDir);
        _lang = model.Language;

        foreach (var ns in model.Namespaces)
        {
            if (string.IsNullOrEmpty(ns.Name))
            {
                // The nameless root namespace renders directly under the language directory:
                // its index.md is the language overview (and the sidebar landing page), listing
                // any child namespaces plus its own type tables. Flat languages (JS/C/Python)
                // are just the degenerate case of a single root namespace and no children.
                WriteLanguageIndex(model, ns, outputDir);
                foreach (var type in ns.Types)
                    WriteTypePage(model, ns, type, outputDir, currentPageDir: "");
            }
            else
            {
                // Named namespaces live in their own folder; each folder page is self-contained
                // (child namespaces + its own types). Languages whose every namespace is named
                // (e.g. C#) have no separate overview page — the sidebar points at the root
                // namespace's folder page as the landing page.
                var nsDir = Path.Combine(outputDir, ns.Name);
                Directory.CreateDirectory(nsDir);
                WriteNamespaceCategory(model, ns, nsDir);
                WriteNamespaceIndex(model, ns, nsDir);
                foreach (var type in ns.Types)
                    WriteTypePage(model, ns, type, nsDir, currentPageDir: ns.Name);
            }
        }
    }

    // ── path / href contract ───────────────────────────────────────────────

    /// <summary>
    /// Page path relative to the language root for a type. Empty <paramref name="namespaceName"/>
    /// (flat languages) → <c>TypeName.md</c>; otherwise <c>Namespace/TypeName.md</c>.
    /// Adapters use this to populate <see cref="ApiTypeRef.Href"/>.
    /// </summary>
    public static string PageHref(string namespaceName, string typeName)
        => string.IsNullOrEmpty(namespaceName) ? $"{typeName}.md" : $"{namespaceName}/{typeName}.md";

    /// <summary>Page path + member anchor, relative to the language root.</summary>
    public static string MemberHref(string namespaceName, string typeName, string anchor)
        => $"{PageHref(namespaceName, typeName)}#{anchor}";

    /// <summary>
    /// Rebase a language-root-relative href onto the directory of the page being rendered.
    /// e.g. ("Velopack.Sources/IFileDownloader.md", currentPageDir:"Velopack") → "../Velopack.Sources/IFileDownloader.md".
    /// </summary>
    private static string Rebase(string rootRelativeHref, string currentPageDir)
    {
        var fragmentIdx = rootRelativeHref.IndexOf('#');
        var fragment = fragmentIdx >= 0 ? rootRelativeHref[fragmentIdx..] : "";
        var path = fragmentIdx >= 0 ? rootRelativeHref[..fragmentIdx] : rootRelativeHref;

        var fromParts = string.IsNullOrEmpty(currentPageDir)
            ? Array.Empty<string>()
            : currentPageDir.Split('/', StringSplitOptions.RemoveEmptyEntries);
        var toParts = path.Split('/', StringSplitOptions.RemoveEmptyEntries);

        // common prefix
        int common = 0;
        while (common < fromParts.Length && common < toParts.Length - 1 &&
               fromParts[common] == toParts[common])
            common++;

        var up = fromParts.Length - common;
        var rel = new List<string>();
        for (int i = 0; i < up; i++) rel.Add("..");
        for (int i = common; i < toParts.Length; i++) rel.Add(toParts[i]);

        var joined = string.Join("/", rel);
        if (joined.Length == 0) joined = ".";
        if (!joined.StartsWith(".")) joined = "./" + joined;
        return joined + fragment;
    }

    private static string RenderTypeRef(ApiTypeRef? type, string currentPageDir)
    {
        if (type == null) return "";
        var name = RenderHelpers.InlineCodeEscape(type.Name);
        if (string.IsNullOrEmpty(type.Href))
            return $"`{name}`";
        return $"[`{name}`]({Rebase(type.Href, currentPageDir)})";
    }

    /// <summary>
    /// Render adapter-produced Markdown body text for a page: first rebase any
    /// language-root-relative links the adapter embedded (from <c>&lt;see cref&gt;</c> etc.)
    /// onto this page's directory, then make it MDX-safe.
    /// </summary>
    private static string RenderBody(string? markdown, string currentPageDir)
    {
        if (string.IsNullOrEmpty(markdown))
            return "";
        var rebased = RebaseBodyLinks(markdown, currentPageDir);
        return RenderHelpers.MdxSafe(rebased);
    }

    private static readonly System.Text.RegularExpressions.Regex LinkRx =
        new(@"\]\(([^)\s]+)\)", System.Text.RegularExpressions.RegexOptions.Compiled);

    private static string RebaseBodyLinks(string markdown, string currentPageDir)
        => LinkRx.Replace(markdown, m =>
        {
            var url = m.Groups[1].Value;
            if (url.StartsWith(".") || url.StartsWith("/") || url.StartsWith("#") ||
                url.Contains("://") || url.StartsWith("mailto:"))
                return m.Value; // already relative / absolute / anchor / external
            return $"]({Rebase(url, currentPageDir)})";
        });

    // ── language overview ──────────────────────────────────────────────────

    /// <summary>
    /// Language-root <c>index.md</c> for the nameless root namespace: the type tables live here
    /// and the page doubles as the sidebar landing page. Any child namespaces (named namespaces
    /// nested under the root, e.g. the C++ <c>Sources</c> folder) are listed above the types.
    /// Languages whose every namespace is named don't use this — see <see cref="WriteNamespaceIndex"/>.
    /// </summary>
    private static void WriteLanguageIndex(ApiModel model, ApiNamespace rootNs, string outputDir)
    {
        var sb = new StringBuilder();
        sb.AppendLine("---");
        sb.AppendLine($"title: {RenderHelpers.YamlScalar(model.DisplayName + " API")}");
        sb.AppendLine("sidebar_label: Overview");
        sb.AppendLine("sidebar_position: 0");
        sb.AppendLine("---");
        sb.AppendLine(AutoGenComment);
        sb.AppendLine();
        sb.AppendLine($"# {model.DisplayName} API Reference");
        sb.AppendLine();
        sb.AppendLine($"**Package:** `{model.PackageName}`{VersionSuffix(model)}");
        sb.AppendLine();

        AppendChildNamespaces(sb, model, rootNs);
        AppendTypeTables(sb, rootNs.Types, currentPageDir: "");

        sb.AppendLine();
        sb.AppendLine("___");
        sb.AppendLine($"*Generated from `{model.PackageName}`{VersionSuffix(model)}*");

        File.WriteAllText(Path.Combine(outputDir, "index.md"), sb.ToString());
    }

    // ── namespace pages ────────────────────────────────────────────────────

    private static void WriteNamespaceCategory(ApiModel model, ApiNamespace ns, string nsDir)
    {
        // unique i18n key: <lang>-<ns-slug>
        var key = $"{model.Language}-{RenderHelpers.KeySegment(ns.Name)}";
        File.WriteAllText(
            Path.Combine(nsDir, "_category_.yml"),
            RenderHelpers.CategoryYml(ns.Name, key));
    }

    private static void WriteNamespaceIndex(ApiModel model, ApiNamespace ns, string nsDir)
    {
        var sb = new StringBuilder();
        sb.AppendLine("---");
        sb.AppendLine($"title: {RenderHelpers.YamlScalar(ns.Name)}");
        sb.AppendLine($"sidebar_label: {RenderHelpers.YamlScalar(ns.Name)}");
        sb.AppendLine("sidebar_position: 0");
        sb.AppendLine("---");
        sb.AppendLine(AutoGenComment);
        sb.AppendLine();
        sb.AppendLine($"# {ns.Name} namespace");
        sb.AppendLine();
        if (!string.IsNullOrWhiteSpace(ns.Summary))
        {
            sb.AppendLine(RenderBody(ns.Summary, ns.Name));
            sb.AppendLine();
        }

        AppendChildNamespaces(sb, model, ns);
        AppendTypeTables(sb, ns.Types, currentPageDir: ns.Name);

        File.WriteAllText(Path.Combine(nsDir, "index.md"), sb.ToString());
    }

    /// <summary>
    /// List the namespaces directly nested under <paramref name="ns"/> at the top of its page, so
    /// the root namespace page doubles as the language overview. "Direct child" means the parent
    /// segment (everything before the last dot) equals <paramref name="ns"/>'s name — so the
    /// nameless root (<c>""</c>) parents top-level names like <c>Sources</c>, and <c>Velopack</c>
    /// parents <c>Velopack.Sources</c> but not <c>Velopack.Sources.Internal</c>. Emits nothing when
    /// the namespace has no children.
    /// </summary>
    private static void AppendChildNamespaces(StringBuilder sb, ApiModel model, ApiNamespace ns)
    {
        var children = model.Namespaces
            .Where(n => n.Name.Length > 0 && ParentNamespace(n.Name) == ns.Name)
            .OrderBy(n => n.Name, StringComparer.Ordinal)
            .ToList();
        if (children.Count == 0)
            return;

        sb.AppendLine("## Namespaces");
        sb.AppendLine();
        var rows = children.Select(n => (IReadOnlyList<string>)new[]
        {
            $"[`{RenderHelpers.InlineCodeEscape(n.Name)}`]({Rebase(n.Name + "/index.md", ns.Name)})",
            RenderHelpers.CellEscape(FirstLine(n.Summary)),
        });
        sb.AppendLine(RenderHelpers.Table(new[] { "Namespace", "Summary" }, rows));
        sb.AppendLine();
    }

    /// <summary>Parent namespace name (everything before the last dot), or <c>""</c> for a top-level name.</summary>
    private static string ParentNamespace(string name)
    {
        var idx = name.LastIndexOf('.');
        return idx >= 0 ? name[..idx] : "";
    }

    /// <summary>Emit one table per non-empty type-kind group (Classes, Structs, …).</summary>
    private static void AppendTypeTables(StringBuilder sb, IReadOnlyList<ApiType> types, string currentPageDir)
    {
        foreach (var (kind, heading) in TypeKindSections)
        {
            var group = types.Where(t => t.Kind == kind)
                             .OrderBy(t => t.Name, StringComparer.Ordinal)
                             .ToList();
            if (group.Count == 0)
                continue;

            sb.AppendLine($"## {heading}");
            sb.AppendLine();
            var rows = group.Select(t => (IReadOnlyList<string>)new[]
            {
                $"[`{RenderHelpers.InlineCodeEscape(t.Name)}`](./{t.Name}.md)" +
                    (t.IsObsolete ? " _(deprecated)_" : ""),
                RenderHelpers.CellEscape(FirstLine(t.Summary)),
            });
            sb.AppendLine(RenderHelpers.Table(new[] { "Type", "Summary" }, rows));
            sb.AppendLine();
        }
    }

    private static readonly (ApiTypeKind Kind, string Heading)[] TypeKindSections =
    {
        (ApiTypeKind.Class, "Classes"),
        (ApiTypeKind.FreeFunctionGroup, "Modules"),
        (ApiTypeKind.Module, "Modules"),
        (ApiTypeKind.Struct, "Structs"),
        (ApiTypeKind.Interface, "Interfaces"),
        (ApiTypeKind.Enum, "Enums"),
        (ApiTypeKind.Delegate, "Delegates"),
    };

    // ── type pages ─────────────────────────────────────────────────────────

    private static void WriteTypePage(ApiModel model, ApiNamespace ns, ApiType type, string dir, string currentPageDir)
    {
        var sb = new StringBuilder();

        sb.AppendLine("---");
        sb.AppendLine($"title: {RenderHelpers.YamlScalar(type.Name)}");
        sb.AppendLine($"sidebar_label: {RenderHelpers.YamlScalar(type.Name)}");
        sb.AppendLine($"sidebar_position: {SidebarPosition(type.Kind)}");
        sb.AppendLine("---");
        sb.AppendLine(AutoGenComment);
        sb.AppendLine();

        sb.AppendLine($"# {type.Name} {KindLabel(type.Kind)}");
        sb.AppendLine();

        // One lightweight metadata line. Package/version live on the overview + footer, so the
        // type page only carries the namespace link (when the language has namespaces).
        if (!string.IsNullOrEmpty(ns.Name))
        {
            sb.AppendLine($"Namespace: [`{RenderHelpers.InlineCodeEscape(ns.Name)}`](./index.md)");
            sb.AppendLine();
        }

        if (type.IsObsolete)
        {
            sb.Append(":::warning Deprecated\n");
            sb.AppendLine(string.IsNullOrWhiteSpace(type.ObsoleteMessage)
                ? "This type is obsolete."
                : RenderBody(type.ObsoleteMessage, currentPageDir));
            sb.AppendLine(":::");
            sb.AppendLine();
        }

        if (!string.IsNullOrWhiteSpace(type.Summary))
        {
            sb.AppendLine(RenderBody(type.Summary, currentPageDir));
            sb.AppendLine();
        }

        if (!string.IsNullOrWhiteSpace(type.Signature))
        {
            sb.AppendLine($"```{model.Language}");
            sb.AppendLine(type.Signature.TrimEnd());
            sb.AppendLine("```");
            sb.AppendLine();
        }

        AppendInheritance(sb, type, currentPageDir);

        if (!string.IsNullOrWhiteSpace(type.Remarks))
        {
            sb.AppendLine("## Remarks");
            sb.AppendLine();
            sb.AppendLine(RenderBody(type.Remarks, currentPageDir));
            sb.AppendLine();
        }

        if (type.Kind == ApiTypeKind.Enum)
            AppendEnumValues(sb, type);
        else
            AppendMembers(sb, type, currentPageDir);

        sb.AppendLine("___");
        sb.AppendLine($"*Generated from `{model.PackageName}`{VersionSuffix(model)}*");

        File.WriteAllText(Path.Combine(dir, type.Name + ".md"), sb.ToString());
    }

    private static void AppendInheritance(StringBuilder sb, ApiType type, string currentPageDir)
    {
        var parts = new List<string>();
        if (type.BaseTypes.Count > 0)
            parts.Add("**Inherits:** " + string.Join(", ", type.BaseTypes.Select(t => RenderTypeRef(t, currentPageDir))));
        if (type.Interfaces.Count > 0)
            parts.Add("**Implements:** " + string.Join(", ", type.Interfaces.Select(t => RenderTypeRef(t, currentPageDir))));
        if (parts.Count == 0)
            return;
        foreach (var p in parts)
            sb.AppendLine(p + "  ");
        sb.AppendLine();
    }

    private static void AppendEnumValues(StringBuilder sb, ApiType type)
    {
        var values = type.Members.Where(m => m.Kind == ApiMemberKind.EnumValue).ToList();
        if (values.Count == 0)
            return;
        sb.AppendLine("## Values");
        sb.AppendLine();
        var rows = values.Select(v => (IReadOnlyList<string>)new[]
        {
            $"`{RenderHelpers.InlineCodeEscape(v.Name)}`",
            RenderHelpers.CellEscape(v.Summary),
        });
        sb.AppendLine(RenderHelpers.Table(new[] { "Name", "Description" }, rows));
        sb.AppendLine();
    }

    private static void AppendMembers(StringBuilder sb, ApiType type, string currentPageDir)
    {
        var usedAnchors = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        // Resolve a stable anchor + display title for every member up-front so the per-kind
        // summary table and the detail headings below always point at the same id.
        var titles = new Dictionary<ApiMember, (string Anchor, string Title)>();
        foreach (var member in type.Members)
        {
            var anchor = UniqueAnchor(member.Anchor ?? RenderHelpers.Anchor(member.Signature ?? member.Name), usedAnchors);
            titles[member] = (anchor, MemberTitle(member));
        }

        foreach (var (kind, heading) in MemberKindSections)
        {
            var group = type.Members.Where(m => m.Kind == kind).ToList();
            if (group.Count == 0)
                continue;

            sb.AppendLine($"## {heading}");
            sb.AppendLine();

            // Summary table (docfx-style): scannable index linking to each member's detail below.
            // The link text drops the parameter list (bare name) to leave more room for the
            // summary; the full signature with params is on the detail heading it jumps to.
            var rows = group.Select(m => (IReadOnlyList<string>)new[]
            {
                $"[`{RenderHelpers.InlineCodeEscape(m.Name)}`](#{titles[m].Anchor})" +
                    (m.IsObsolete ? " _(deprecated)_" : ""),
                RenderHelpers.CellEscape(FirstLine(m.Summary)),
            });
            sb.AppendLine(RenderHelpers.Table(new[] { Singular(heading), "Summary" }, rows));
            sb.AppendLine();

            foreach (var member in group)
                AppendMember(sb, member, currentPageDir, titles[member]);
        }
    }

    /// <summary>
    /// Display title for a member. Callables show their parameter names so overloads are
    /// distinguishable (e.g. <c>WaitExitThenApplyUpdates(asset, silent, restart, args)</c>);
    /// everything else uses the bare member name.
    /// </summary>
    private static string MemberTitle(ApiMember member)
    {
        bool callable = member.Kind is ApiMemberKind.Method or ApiMemberKind.Constructor or ApiMemberKind.Operator;
        if (!callable)
            return member.Name;
        return $"{member.Name}({string.Join(", ", member.Parameters.Select(p => p.Name))})";
    }

    private static string Singular(string heading) => heading switch
    {
        "Properties" => "Property",
        _ => heading.EndsWith("s") ? heading[..^1] : heading,
    };

    private static readonly (ApiMemberKind Kind, string Heading)[] MemberKindSections =
    {
        (ApiMemberKind.Constructor, "Constructors"),
        (ApiMemberKind.Property, "Properties"),
        (ApiMemberKind.Method, "Methods"),
        (ApiMemberKind.Field, "Fields"),
        (ApiMemberKind.Event, "Events"),
        (ApiMemberKind.Operator, "Operators"),
    };

    private static void AppendMember(StringBuilder sb, ApiMember member, string currentPageDir, (string Anchor, string Title) info)
    {
        sb.AppendLine($"### {RenderHelpers.InlineCodeEscape(info.Title)} {{#{info.Anchor}}}");
        sb.AppendLine();

        if (member.IsObsolete)
        {
            sb.Append(":::warning Deprecated\n");
            sb.AppendLine(string.IsNullOrWhiteSpace(member.ObsoleteMessage)
                ? "This member is obsolete."
                : RenderBody(member.ObsoleteMessage, currentPageDir));
            sb.AppendLine(":::");
            sb.AppendLine();
        }

        if (!string.IsNullOrWhiteSpace(member.Signature))
        {
            sb.AppendLine("```" + (_lang ?? ""));
            sb.AppendLine(member.Signature!.TrimEnd());
            sb.AppendLine("```");
            sb.AppendLine();
        }

        if (member.Modifiers.Count > 0)
        {
            sb.AppendLine(string.Join(" ", member.Modifiers.Select(m => $"`{m}`")));
            sb.AppendLine();
        }

        if (!string.IsNullOrWhiteSpace(member.Summary))
        {
            sb.AppendLine(RenderBody(member.Summary, currentPageDir));
            sb.AppendLine();
        }

        AppendParameters(sb, member, currentPageDir);

        // The type of a property/field is already shown in its signature, so only callables
        // surface a Returns line (and only when there is a type or a description to show).
        bool callable = member.Kind is ApiMemberKind.Method or ApiMemberKind.Constructor or ApiMemberKind.Operator;
        if (callable && member.Returns != null &&
            (member.Returns.Type != null || !string.IsNullOrWhiteSpace(member.Returns.Description)))
        {
            var typePart = RenderTypeRef(member.Returns.Type, currentPageDir);
            var descPart = RenderBody(member.Returns.Description, currentPageDir);
            sb.Append("**Returns** ");
            if (!string.IsNullOrEmpty(typePart)) sb.Append(typePart);
            if (!string.IsNullOrEmpty(descPart)) sb.Append(string.IsNullOrEmpty(typePart) ? "" : " — ").Append(descPart);
            sb.AppendLine();
            sb.AppendLine();
        }

        if (!string.IsNullOrWhiteSpace(member.Remarks))
        {
            sb.AppendLine(RenderBody(member.Remarks, currentPageDir));
            sb.AppendLine();
        }
    }

    /// <summary>Render a member's parameter table, dropping the Type column when no type is known (e.g. C++).</summary>
    private static void AppendParameters(StringBuilder sb, ApiMember member, string currentPageDir)
    {
        if (member.Parameters.Count == 0)
            return;

        sb.AppendLine("**Parameters**");
        sb.AppendLine();

        bool anyType = member.Parameters.Any(p => p.Type != null);
        if (anyType)
        {
            var rows = member.Parameters.Select(p => (IReadOnlyList<string>)new[]
            {
                $"`{RenderHelpers.InlineCodeEscape(p.Name)}`",
                RenderTypeRef(p.Type, currentPageDir),
                RenderHelpers.CellEscape(ParamDesc(p)),
            });
            sb.AppendLine(RenderHelpers.Table(new[] { "Name", "Type", "Description" }, rows));
        }
        else
        {
            var rows = member.Parameters.Select(p => (IReadOnlyList<string>)new[]
            {
                $"`{RenderHelpers.InlineCodeEscape(p.Name)}`",
                RenderHelpers.CellEscape(ParamDesc(p)),
            });
            sb.AppendLine(RenderHelpers.Table(new[] { "Name", "Description" }, rows));
        }
        sb.AppendLine();
    }

    private static string ParamDesc(ApiParameter p)
    {
        var desc = p.Description ?? "";
        if (!string.IsNullOrEmpty(p.Default))
            desc = (desc.Length > 0 ? desc + " " : "") + $"(default: {p.Default})";
        else if (p.Optional)
            desc = (desc.Length > 0 ? desc + " " : "") + "(optional)";
        return desc;
    }

    private static string UniqueAnchor(string baseAnchor, HashSet<string> used)
    {
        var anchor = baseAnchor;
        int i = 2;
        while (!used.Add(anchor))
            anchor = $"{baseAnchor}-{i++}";
        return anchor;
    }

    // ── small helpers ──────────────────────────────────────────────────────

    private static string VersionSuffix(ApiModel model)
        => string.IsNullOrEmpty(model.Version) ? "" : $" {model.Version}";

    private static string? FirstLine(string? text)
    {
        if (string.IsNullOrWhiteSpace(text))
            return text;
        var idx = text.IndexOf('\n');
        return idx >= 0 ? text[..idx] : text;
    }

    private static string KindLabel(ApiTypeKind kind) => kind switch
    {
        ApiTypeKind.Class => "class",
        ApiTypeKind.Struct => "struct",
        ApiTypeKind.Interface => "interface",
        ApiTypeKind.Enum => "enum",
        ApiTypeKind.Delegate => "delegate",
        ApiTypeKind.FreeFunctionGroup => "module",
        ApiTypeKind.Module => "module",
        _ => "type",
    };

    private static int SidebarPosition(ApiTypeKind kind) => kind switch
    {
        ApiTypeKind.Class => 2,
        ApiTypeKind.FreeFunctionGroup => 2,
        ApiTypeKind.Module => 2,
        ApiTypeKind.Struct => 3,
        ApiTypeKind.Interface => 4,
        ApiTypeKind.Delegate => 4,
        ApiTypeKind.Enum => 5,
        _ => 9,
    };
}
