using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using DocGenerator.Markdown;
using DocGenerator.Model;

namespace DocGenerator.Languages.Cpp;

/// <summary>
/// Converts the standardese XML for <c>Velopack.hpp</c> into the unified <see cref="ApiModel"/>.
/// The C++ API lives in a single <c>namespace Velopack</c>, so we treat it as a flat language:
/// each documented <c>class</c>/<c>struct</c> becomes a type page, and its nested member functions
/// / constructors / fields become members.
///
/// <para>standardese's XML is a presentation token stream (each declaration is a sequence of
/// <c>code-block-keyword</c> / <c>code-block-identifier</c> / <c>code-block-punctuation</c> /
/// <c>soft-break</c> nodes) rather than a semantic model. <see cref="RenderSynopsis"/> rebuilds a
/// readable declaration from it; entity kind comes from the section heading
/// ("Struct" / "Class" / "Function" / "Constructor" / …) and the id encodes the fully-qualified
/// name (e.g. <c>Velopack::UpdateManager::CheckForUpdates()</c>).</para>
/// </summary>
internal static class CppAdapter
{
    private const string AutoGenComment = "<!-- auto-generated by generator/ — do not edit -->";

    public static ApiModel Build(CppExtractResult extract)
    {
        var entities = new Dictionary<string, CppEntity>(StringComparer.Ordinal);
        foreach (var xmlFile in Directory.GetFiles(extract.XmlDir, "doc_*.xml"))
        {
            XDocument doc;
            try { doc = XDocument.Load(xmlFile); }
            catch { continue; }
            foreach (var ed in doc.Descendants().Where(e => e.Name.LocalName == "entity-documentation"))
            {
                var id = (string?)ed.Attribute("id");
                if (string.IsNullOrEmpty(id) || entities.ContainsKey(id))
                    continue;
                var entity = ParseEntity(id, ed);
                if (entity != null)
                    entities[id] = entity;
            }
        }

        // Types: classes/structs directly under the Velopack namespace (exactly one "::", no "(").
        // C++ has no real sub-namespaces, but the update-source types form an obvious family, so
        // we lift them into a synthetic "Sources" namespace (rendered as a Sources/ sub-folder)
        // while everything else stays at the language root. This is a presentation grouping only.
        var types = new List<ApiType>();
        foreach (var e in entities.Values.Where(e => e.IsType))
        {
            var memberEntities = entities.Values
                .Where(m => m.Id.StartsWith(e.Id + "::", StringComparison.Ordinal) && !m.IsType)
                .ToList();
            var ns = IsSourceName(ShortName(e.Id)) ? "Sources" : "";
            types.Add(BuildType(e, memberEntities, ns));
        }

        var namespaces = new List<ApiNamespace>
        {
            new() { Name = "", Types = TypesIn(types, "") },
        };
        var sourceTypes = TypesIn(types, "Sources");
        if (sourceTypes.Count > 0)
            namespaces.Add(new()
            {
                Name = "Sources",
                Summary = "Built-in and custom update sources for fetching release feeds and downloading assets.",
                Types = sourceTypes,
            });

        return new ApiModel
        {
            Language = "cpp",
            DisplayName = "C++",
            PackageName = "Velopack (C++ headers)",
            Version = extract.Version,
            Namespaces = namespaces,
        };
    }

    /// <summary>Update-source types (anything whose name contains "Source") are grouped together.</summary>
    private static bool IsSourceName(string name) => name.Contains("Source", StringComparison.Ordinal);

    private static List<ApiType> TypesIn(IEnumerable<ApiType> types, string ns)
        => types.Where(t => t.Namespace == ns).OrderBy(t => t.Name, StringComparer.Ordinal).ToList();

    private static ApiType BuildType(CppEntity e, List<CppEntity> memberEntities, string ns)
    {
        var members = new List<ApiMember>();

        foreach (var m in memberEntities)
        {
            var kind = m.Kind switch
            {
                "Constructor" => ApiMemberKind.Constructor,
                "Function" => ApiMemberKind.Method,
                "Member" => ApiMemberKind.Method, // "Member function"
                "Variable" => ApiMemberKind.Field,
                _ => (ApiMemberKind?)null,
            };
            if (kind == null) // Destructor / Type alias / etc. — skip
                continue;
            members.Add(BuildMember(m, kind.Value));
        }

        // Struct/class fields are surfaced by standardese as a "Member variables" list on the
        // type itself (name + description); add any not already present as Variable entities.
        var have = new HashSet<string>(members.Select(x => x.Name), StringComparer.Ordinal);
        foreach (var (name, desc) in e.MemberVars)
        {
            if (have.Add(name))
                members.Add(new ApiMember
                {
                    Kind = ApiMemberKind.Field,
                    Name = name,
                    Summary = desc,
                    Anchor = RenderHelpers.Anchor(name),
                });
        }

        return new ApiType
        {
            Kind = e.Kind == "Struct" ? ApiTypeKind.Struct : ApiTypeKind.Class,
            Name = ShortName(e.Id),
            FullName = e.Id,
            Namespace = ns,
            Summary = e.Summary,
            Remarks = e.Remarks,
            Signature = DeclarationLine(e.Synopsis),
            Members = members,
        };
    }

    private static ApiMember BuildMember(CppEntity e, ApiMemberKind kind)
    {
        var (summary, parameters, returns) = SplitDoc(e.Summary, e.Remarks);
        return new ApiMember
        {
            Kind = kind,
            Name = MemberShortName(e.Id),
            Signature = e.Synopsis,
            Summary = summary,
            Parameters = parameters,
            Returns = returns,
            Anchor = RenderHelpers.Anchor(e.Id),
        };
    }

    // ── doc text: pull @param / @returns out of the doxygen-style comment ────────

    private static (string? summary, List<ApiParameter> parameters, ApiReturn? returns) SplitDoc(string? brief, string? details)
    {
        var text = string.Join("\n\n", new[] { brief, details }.Where(s => !string.IsNullOrWhiteSpace(s)));
        if (string.IsNullOrWhiteSpace(text))
            return (null, new List<ApiParameter>(), null);

        var parameters = new List<ApiParameter>();
        ApiReturn? returns = null;

        foreach (Match m in Regex.Matches(text, @"@param\s+(?<name>\S+)\s+(?<desc>.*?)(?=@param\b|@returns?\b|$)", RegexOptions.Singleline))
            parameters.Add(new ApiParameter { Name = m.Groups["name"].Value.Trim(), Description = Clean(m.Groups["desc"].Value) });

        var ret = Regex.Match(text, @"@returns?\s+(?<desc>.*?)(?=@param\b|$)", RegexOptions.Singleline);
        if (ret.Success)
            returns = new ApiReturn { Description = Clean(ret.Groups["desc"].Value) };

        // Summary is whatever precedes the first doxygen tag.
        var firstTag = Regex.Match(text, @"@(param|returns?)\b");
        var summary = firstTag.Success ? text[..firstTag.Index] : text;
        return (Clean(summary), parameters, returns);
    }

    private static string? Clean(string? s)
    {
        if (string.IsNullOrWhiteSpace(s)) return null;
        s = Regex.Replace(s, @"\s+", " ").Trim();
        return s.Length == 0 ? null : s;
    }

    // ── entity parsing ───────────────────────────────────────────────────────

    private static CppEntity? ParseEntity(string id, XElement ed)
    {
        var headingText = TextOf(ed.Elements().FirstOrDefault(e => e.Name.LocalName == "heading"));
        var kind = headingText?.Trim().Split(' ', StringSplitOptions.RemoveEmptyEntries).FirstOrDefault() ?? "";

        var codeBlock = ed.Elements().FirstOrDefault(e => e.Name.LocalName == "code-block");
        var synopsis = codeBlock != null ? RenderSynopsis(codeBlock) : null;

        var brief = TextOf(ed.Elements().FirstOrDefault(e => e.Name.LocalName == "brief-section"));
        var details = TextOf(ed.Elements().FirstOrDefault(e => e.Name.LocalName == "details-section"));

        var memberVars = new List<(string, string)>();
        foreach (var list in ed.Elements().Where(e => e.Name.LocalName == "list-section"))
        {
            foreach (var item in list.Descendants().Where(e => e.Name.LocalName == "term-description-item"))
            {
                var term = TextOf(item.Elements().FirstOrDefault(e => e.Name.LocalName == "term"));
                var desc = TextOf(item.Elements().FirstOrDefault(e => e.Name.LocalName == "description"));
                if (!string.IsNullOrWhiteSpace(term))
                    memberVars.Add((term!.Trim(), Clean(desc) ?? ""));
            }
        }

        // One "::" and a type kind ⇒ a top-level class/struct; "Velopack" namespace pseudo-entity excluded.
        var isType = (kind == "Class" || kind == "Struct")
                     && CountOccurrences(id, "::") == 1
                     && !id.Contains('(');

        return new CppEntity
        {
            Id = id,
            Kind = kind,
            Synopsis = synopsis,
            Summary = Clean(brief),
            Remarks = Clean(details),
            MemberVars = memberVars,
            IsType = isType,
        };
    }

    /// <summary>Rebuild a readable declaration from a standardese code-block token stream.</summary>
    private static string RenderSynopsis(XElement codeBlock)
    {
        var sb = new StringBuilder();

        // standardese's own inter-token whitespace is inconsistent, so we drop it and recompute
        // spacing from token adjacency. Each appended token is one keyword/identifier/literal/
        // punctuation chunk; NeedSpace decides whether a space precedes it.
        void Append(string text)
        {
            text = text.Trim();
            if (text.Length == 0) return;
            if (sb.Length > 0 && sb[^1] != '\n' && NeedSpace(sb[^1], text[0]))
                sb.Append(' ');
            sb.Append(text);
        }

        void Walk(XNode node)
        {
            switch (node)
            {
                case XText t:
                    Append(t.Value); // bare type names sometimes appear as raw text
                    break;
                case XElement e:
                    var ln = e.Name.LocalName;
                    if (ln == "soft-break") sb.Append('\n');
                    else if (ln.StartsWith("code-block-")) Append(e.Value);
                    else foreach (var c in e.Nodes()) Walk(c); // documentation-link, emphasis, …
                    break;
            }
        }

        foreach (var n in codeBlock.Nodes()) Walk(n);

        var s = sb.ToString();
        s = Regex.Replace(s, @"[ \t]+\n", "\n");
        s = Regex.Replace(s, @"\n{2,}", "\n");
        return s.Trim();
    }

    private static bool IsWord(char c) => char.IsLetterOrDigit(c) || c == '_';

    /// <summary>Should a space separate a token ending in <paramref name="la"/> from one starting with <paramref name="fb"/>?</summary>
    private static bool NeedSpace(char la, char fb)
    {
        if (IsWord(la) && IsWord(fb)) return true;            // "const" "T"      -> "const T"
        if (la == '=' || fb == '=') return true;              // "options" "=" "nullptr"
        if (la == ',' && fb != ')') return true;              // "," "size_t"     -> ", size_t"
        if ((la is ')' or '>' or '&' or '*') && IsWord(fb)) return true; // "&" "x" -> "& x", ">" "p" -> "> p"
        return false;
    }

    /// <summary>First declaration line of a synopsis (up to the body <c>{</c>), for type signatures.</summary>
    private static string DeclarationLine(string? synopsis)
    {
        if (string.IsNullOrWhiteSpace(synopsis)) return "";
        var head = synopsis;
        var brace = head.IndexOf('{');
        if (brace >= 0) head = head[..brace];
        head = head.Replace("\n", " ");
        return Regex.Replace(head, @"\s+", " ").Trim().TrimEnd(';', ':').Trim();
    }

    private static string TextOf(XElement? el) => el == null ? "" : el.Value;

    private static int CountOccurrences(string s, string sub)
    {
        int count = 0, i = 0;
        while ((i = s.IndexOf(sub, i, StringComparison.Ordinal)) >= 0) { count++; i += sub.Length; }
        return count;
    }

    /// <summary>
    /// Short name from an entity id. The signature/template suffix is stripped <b>first</b> — the
    /// parameter list can itself contain <c>::</c> (e.g.
    /// <c>UpdateManager::UpdateManager(std::string const&amp;, Velopack::UpdateOptions const*)</c>) which
    /// would otherwise be mistaken for the name separator.
    /// </summary>
    private static string ShortName(string id)
    {
        var name = StripSuffix(id);
        var idx = name.LastIndexOf("::", StringComparison.Ordinal);
        return idx >= 0 ? name[(idx + 2)..] : name;
    }

    /// <summary>Member name from a fully-qualified member id (drops the type prefix + signature).</summary>
    private static string MemberShortName(string id) => ShortName(id);

    private static string StripSuffix(string name)
    {
        var paren = name.IndexOf('(');
        if (paren >= 0) name = name[..paren];
        var angle = name.IndexOf('<');
        if (angle >= 0) name = name[..angle];
        return name.Trim();
    }

    // ── C API page (verbatim standardese commonmark) ─────────────────────────

    /// <summary>
    /// Write the single "C API" page from standardese's commonmark dump of <c>Velopack.h</c>.
    /// The raw <c>vpkc_*</c> ABI is a flat list with nothing to model, so we embed standardese's
    /// own markdown rather than re-deriving structure — just swapping its <c>H1</c> for frontmatter
    /// and a short note steering most users to the C++ API.
    /// </summary>
    public static void WriteCApiPage(CppExtractResult extract, string outputDir)
    {
        if (extract.CApiMarkdownFile == null || !File.Exists(extract.CApiMarkdownFile))
            return;

        var body = File.ReadAllText(extract.CApiMarkdownFile);
        // Drop standardese's "# Header file `Velopack.h`" title (+ any BOM) and self-doc links.
        body = Regex.Replace(body, @"\A﻿?#\s+Header file[^\n]*\r?\n+", "");
        body = body.Replace("doc_Velopack.md#", "#");
        // standardese leaves doxygen @param/@returns tags inline on a single line; break them out
        // into a bullet list so each parameter and the return value are readable on their own.
        body = FormatDoxygenTags(body);

        var version = string.IsNullOrEmpty(extract.Version) ? "" : $" {extract.Version}";
        var sb = new StringBuilder();
        sb.AppendLine("---");
        sb.AppendLine("title: C API");
        sb.AppendLine("sidebar_label: C API");
        sb.AppendLine("sidebar_position: 8");
        sb.AppendLine("---");
        sb.AppendLine(AutoGenComment);
        sb.AppendLine();
        sb.AppendLine("# C API");
        sb.AppendLine();
        sb.AppendLine(":::info");
        sb.AppendLine("This is the low-level C ABI (`vpkc_*` functions, declared in `Velopack.h`), suitable " +
                      "for C projects and for calling from other languages via FFI / p/invoke. Most C++ " +
                      "projects should prefer the idiomatic C++ classes documented on the other pages.");
        sb.AppendLine(":::");
        sb.AppendLine();
        sb.Append(body.TrimStart());

        File.WriteAllText(Path.Combine(outputDir, "c-api.md"), sb.ToString());
    }

    /// <summary>
    /// Rewrite each line that standardese emits as a run of inline doxygen tags
    /// (<c>@param name desc … @returns desc</c>) into a Markdown bullet list, one bullet per
    /// parameter plus a final "Returns" bullet. Parameter names are unescaped so they render
    /// inside a code span (standardese escapes underscores as <c>\_</c>).
    /// </summary>
    private static string FormatDoxygenTags(string body)
        => Regex.Replace(body, @"(?m)^[ \t]*@(?:param|returns?)\b.*$", m => FormatDoxygenLine(m.Value));

    private static string FormatDoxygenLine(string line)
    {
        var sb = new StringBuilder();
        sb.Append('\n'); // ensure a blank line separates the list from the preceding prose
        foreach (Match p in Regex.Matches(line, @"@param\s+(?<name>\S+)\s+(?<desc>.*?)(?=@param\b|@returns?\b|$)"))
            sb.Append($"- **`{Unescape(p.Groups["name"].Value)}`** — {p.Groups["desc"].Value.Trim()}\n");

        var ret = Regex.Match(line, @"@returns?\s+(?<desc>.*?)(?=@param\b|$)");
        if (ret.Success)
            sb.Append($"- **Returns** — {ret.Groups["desc"].Value.Trim()}\n");

        return sb.ToString().TrimEnd('\n');
    }

    /// <summary>Strip Markdown backslash-escapes (e.g. <c>psz\_error</c> → <c>psz_error</c>) for use in a code span.</summary>
    private static string Unescape(string s) => Regex.Replace(s, @"\\(.)", "$1");

    private sealed class CppEntity
    {
        public required string Id { get; init; }
        public required string Kind { get; init; }
        public string? Synopsis { get; init; }
        public string? Summary { get; init; }
        public string? Remarks { get; init; }
        public List<(string Name, string Desc)> MemberVars { get; init; } = new();
        public bool IsType { get; init; }
    }
}
